import { mount, flushPromises } from '@vue/test-utils'
import { beforeEach, describe, expect, it, vi } from 'vitest'
const api = vi.hoisted(() => ({ listTimeSessions: vi.fn(), createTimeSession: vi.fn(), editTimeSession: vi.fn(), deleteTimeSession: vi.fn() }))
vi.mock('../../api/client', () => ({ timeTrackingApi: api }))
vi.mock('../../composables/useSession', () => ({ useSession: () => ({ authentication: { value: { company: { timezone: 'Asia/Shanghai' } } } }) }))
vi.mock('../../composables/useTimeTracker', () => ({ formatDuration: () => '0:00:01', timerMutation: (_: string, call: (key: string, csrf: string) => unknown) => call('key', 'csrf') }))
import TimeSessionDialog from './TimeSessionDialog.vue'
const record = (id: string, canEdit = true) => ({ id, source: 'MANUAL', rowVersion: 0, displayName: '测试成员', startedAt: new Date('2026-08-01T01:00:00Z'), stoppedAt: new Date('2026-08-01T01:00:01Z'), durationMs: 1000, canEdit, etag: id })
const page = (items = [record('one')], nextCursor: string | null = null) => ({ items, nextCursor, canCreate: true, summary: { totalDurationMs: 1000 } })
async function setup() {
  const wrapper = mount(TimeSessionDialog, { props: { workItemId: 'item', title: '测试' } })
  await flushPromises()
  return wrapper
}
beforeEach(() => { vi.resetAllMocks(); api.listTimeSessions.mockResolvedValue(page()); api.deleteTimeSession.mockResolvedValue({}) })
describe('计时日志分页与写入', () => {
  it('滚动触底追加下一页，并阻止重复加载', async () => {
    api.listTimeSessions.mockResolvedValueOnce(page([record('one')], 'next'))
    const wrapper = await setup()
    let resolve!: (value: unknown) => void
    api.listTimeSessions.mockImplementationOnce(() => new Promise(done => { resolve = done }))
    await wrapper.get('.log-body').trigger('scroll')
    await wrapper.get('.log-body').trigger('scroll')
    expect(api.listTimeSessions).toHaveBeenCalledTimes(2)
    expect(api.listTimeSessions).toHaveBeenLastCalledWith({ workItemId: 'item', cursor: 'next' })
    resolve(page([record('two')]))
    await flushPromises()
    expect(wrapper.findAll('.log-row')).toHaveLength(2)
    wrapper.unmount()
  })
  it('清除遍历未加载分页，只删除有编辑权限的已停止记录', async () => {
    const wrapper = await setup()
    api.listTimeSessions.mockResolvedValueOnce(page([record('one'), record('other', false)], 'next')).mockResolvedValueOnce(page([record('two')])).mockResolvedValueOnce(page([]))
    await wrapper.get('header button').trigger('click')
    await wrapper.get('input').setValue('验收清理')
    await wrapper.get('form').trigger('submit')
    await flushPromises()
    expect(api.deleteTimeSession.mock.calls.map(call => call[0].sessionId)).toEqual(['one', 'two'])
    expect(wrapper.text()).toContain('暂无计时记录')
    wrapper.unmount()
  })
  it('日期和时间可编辑，分钟输入无需修正原因并保留修改标色', async () => {
    api.listTimeSessions.mockResolvedValue(page([{ ...record('one'), source: 'MANUAL', rowVersion: 1, stoppedAt: new Date('2026-08-01T02:00:00Z') }]))
    const wrapper = await setup()
    expect(wrapper.get('.record-date').classes()).toContain('is-edited')
    expect(wrapper.get('.time-range').classes()).toContain('is-edited')
    expect(wrapper.find('[title]').exists()).toBe(false)
    await wrapper.get('.record-date').trigger('click')
    expect(wrapper.text()).toContain('编辑时长记录')
    expect(wrapper.text()).not.toContain('修正原因')
    expect(wrapper.get('input[type="time"]').attributes('step')).toBe('60')
    await wrapper.get('header button').trigger('click')
    await wrapper.get('.time-range').trigger('click')
    await wrapper.get('form').trigger('submit')
    await flushPromises()
    expect(api.editTimeSession).toHaveBeenCalledOnce()
    expect(api.editTimeSession.mock.calls[0]?.[0].timeTrackingCommand).not.toHaveProperty('reason')
    wrapper.unmount()
  })
  it('手动添加成功后重新加载日志', async () => {
    const wrapper = await setup()
    await wrapper.get('.add-session button').trigger('click')
    await wrapper.get('form').trigger('submit')
    await flushPromises()
    expect(api.createTimeSession).toHaveBeenCalledOnce()
    expect(api.createTimeSession.mock.calls[0]?.[0].timeTrackingCommand).not.toHaveProperty('reason')
    expect(api.listTimeSessions).toHaveBeenCalledTimes(2)
    expect(wrapper.find('form').exists()).toBe(false)
    wrapper.unmount()
  })
})
